services:
  app:
    build: .
    container_name: abc-php-main
    expose:
      - "80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=abc-db-main
      - DB_NAME=abc_db
      - DB_USER=postgres
      - DB_PASS=postgres_password
    depends_on:
      - db
    networks:
      - abc-network

  db:
    image: postgres:16-alpine
    container_name: abc-db-main
    environment:
      - POSTGRES_DB=abc_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - abc-network

  nginx:
    image: nginx:latest
    container_name: abc-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - abc-network

  certbot:
    image: certbot/certbot
    container_name: abc-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - abc-network

networks:
  abc-network:
    driver: bridge

volumes:
  db_data:
